blueprint:
  name: Presence Light - On
  description: Turn on a light when presence is detected and it's dark.
  domain: automation
  input:
    presence_entity:
      name: Presence Sensor
      description: Presence sensor device
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    light_sensor:
      name: Light sensor
      description: Light sensor to read from
      default: []
      selector:
        entity:
          domain:
            - sensor
          device_class:
            - illuminance
          multiple: false
    light_threshold:
      name: Light threshold
      description: Light sensor‘s threshold
      default: 1
      selector:
        number:
          min: 0
          max: 255
    light_target:
      name: Light
      description: Light device
      selector:
        target:
          entity:
            domain: light
    bright_percentage:
      name: Bright Percentage
      description: Brightness level that the light will turn into once is turned on
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: percentage

trigger:
  - trigger: state
    entity_id: !input presence_entity
    from: "off"
    to: "on"
  - trigger: numeric_state
    entity_id: !input light_sensor
    below: !input light_threshold

conditions:
  - and:
    - condition: state
      entity_id: !input light_target
      state: "off"
    - condition: state
      entity_id: !input presence_entity
      state: "off"
    - condition: numeric_state
      entity_id: !input light_sensor
      below: !input light_threshold

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
    data:
      brightness_pct: !input bright_percentage
